spring:
  application:
    name: leaderboard-service
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard_db
    username: fightclub
    password: fightclub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: leaderboard-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fight_club.arena_service.dto,com.figth_club.leaderboard_service.dtos"



server:
  port: 8085


services:
  character:
    url: http://character-service:8082

