spring:
  application:
    name: character-service
  datasource:
    url: jdbc:postgresql://localhost:5432/character_db
    username: fightclub
    password: fightclub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db.migrations
    baseline-on-migrate: true

server:
  port: 8082
